version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Build Containers
          command: |
            cd docker
            apk add --update py-pip
            python -m pip install --upgrade pip

            docker build -t tensorlayer_py2_cpu python2/cpu
            docker build -t tensorlayer_py2_gpu python2/gpu
            docker build -t tensorlayer_py3_cpu python3/cpu
            docker build -t tensorlayer_py3_gpu python3/gpu
      - deploy:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            TL_VERSION="$(python pypi_list.py --package tensorlayer --nth_last_version 1)"
            TF_VERSION="$(python pypi_list.py --package tensorflow --nth_last_version 1)"

            CONTAINER_TAG="nightly-py2-cpu"
            docker tag tensorlayer_py2_cpu:latest tensorlayer/tensorlayer:$CONTAINER_TAG
            docker push tensorlayer/tensorlayer:$CONTAINER_TAG

            CONTAINER_TAG="nightly-py2-gpu"
            docker tag tensorlayer_py2_gpu:latest tensorlayer/tensorlayer:$CONTAINER_TAG
            docker push tensorlayer/tensorlayer:$CONTAINER_TAG

            CONTAINER_TAG="nightly-py3-cpu"
            docker tag tensorlayer_py3_cpu:latest tensorlayer/tensorlayer:$CONTAINER_TAG
            docker push tensorlayer/tensorlayer:$CONTAINER_TAG

            CONTAINER_TAG="nightly-py3-gpu"
            docker tag tensorlayer_py3_gpu:latest tensorlayer/tensorlayer:$CONTAINER_TAG
            docker push tensorlayer/tensorlayer:$CONTAINER_TAG